name: CI

on:
  push:

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-20.04, macos-latest]
        pair:
          - elixir: 1.11.3
            otp: 23.2.7
    steps:
      - uses: wojtekmach/beamup/setup-beam@master
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - run: elixir --version
      - run: elixir -e 'IO.inspect :crypto.version()'
