name: CI

on:
  push:

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04]
    steps:
      - uses: erlef/setup-elixir@v1
      - run: elixir --version
      - run: elixir -e 'IO.inspect :crypto.version()'
