name: CI

on:
  push:

jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        pair:
          - elixir: 1.5.3
            otp: 18.3.4.11
          - elixir: 1.7.4
            otp: 19.3.6.13
          - elixir: 1.9.4
            otp: 20.3.8.26
          - elixir: 1.11.3
            otp: 21.3.8.21
          - elixir: 1.11.3
            otp: 23.2.7
          - elixir: 1.12.0-rc.0
            otp: 24.0-rc2
    steps:
      - uses: erlef/setup-elixir@v1.7
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - run: elixir -e ':inets.start(); :ssl.start(); IO.inspect :httpc.request(:head, {~c"https://api.github.com", [{~c"user-agent", ~c"httpc"}]}, [], [])'
